# Generated by Django 3.0.6 on 2020-05-31 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones_CAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_acopio_opciones', models.CharField(choices=[('TM', 'Timbire'), ('BR', 'Borbon'), ('CE', 'Colon Eloy'), ('SG', 'San Gregorio')], default='SG', max_length=2)),
                ('cedula_productor', models.CharField(default='', help_text='Ingrese numero de cedula del producto', max_length=10, null=True)),
                ('cedula_vendedor', models.CharField(default='na', help_text='Ingrese numero de cedula del comercialnte o transportista', max_length=10, null=True)),
                ('certificacion_opciones', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('Transición', 'En procesos de transición')], default='Si', max_length=10, null=True)),
                ('Tipo_certificacion_opciones', models.CharField(choices=[('Organica', 'Organica'), ('Comercio Justo / Fair Trade - FLO', 'Comercio Justo / Fair Trade - FLO'), ('Rain Forest', 'Rain Forest'), ('Nat', 'Naturland'), ('Pequeños Productores SPP', 'Pequeños Productores SPP'), ('Otra', 'Otra'), ('No aplica', 'No aplica')], default='Organica', max_length=100, null=True)),
                ('Tipo_cacao_opciones', models.CharField(choices=[('Nacional', 'Nacional'), ('CCN-51', 'CCN-51'), ('Criollo', 'Criollo'), ('Mix de variedades', 'Mix de variedades'), ('Otro', 'Otro')], default='Nacional', max_length=100, null=True)),
                ('Tipo_especialidad_opciones', models.CharField(choices=[('Genetica', 'Genetica'), ('Origen', 'Origen'), ('Tratamiento', 'Tratamiento'), ('Organoléptica', 'Organoléptica'), ('Otro', 'Otro')], default='Origen', max_length=100, null=True)),
                ('estado_cacao_opciones', models.CharField(choices=[('Seco, humedad <2%', 'Seco, humedad <2%'), ('Semiseco humedad entre 15% al 20%', 'Semiseco humedad entre 15% al 20%'), ('Humedad superior al 20%', 'Humedad superior al 20%'), ('Lote con diferentes grados de humedad', 'Lote con diferentes grados de humedad'), ('Otro', 'Otro')], default='Seco, humedad <2%', max_length=100, null=True)),
                ('fecha_compra_venta', models.DateField(blank=True, null=True)),
                ('fecha_inicio_cosecha', models.DateField(blank=True, null=True)),
                ('fecha_fin_cosecha', models.DateField(blank=True, null=True)),
                ('fermentacion_lote', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True)),
                ('tipo_fermentacion_opciones', models.CharField(choices=[('Saco', 'Saco'), ('Caja de fermentación', 'Caja de fermentacion'), ('Lona', 'Lona'), ('Otro', 'Otro')], default='Saco', max_length=100, null=True)),
                ('tiempo_fermentacion', models.CharField(help_text='Ingrese tiempo de fermentacion en dias y horas', max_length=20, null=True)),
                ('tipo_secado_opciones', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Secado Natural con Sol', 'Secado Natural con Sol'), ('Secado Natural en sombra', 'Secado Natural en sombra'), ('Secado a gas', 'Secado a gas')], default='Secado Natural con Sol', max_length=100, null=True)),
                ('modo_secado_opciones', models.CharField(choices=[('Lona', 'Lona'), ('Marquesina', 'Marquesina'), ('Bandeja de secado', 'Bandeja de secado'), ('Otra', 'Otra')], default='Lona', max_length=100, null=True)),
                ('tiempo_secado', models.CharField(help_text='Ingrese tiempo del proceso de secado: dias y horas para secado natural /horas para secado a gas', max_length=20, null=True)),
                ('tipo_transporte_opciones', models.CharField(choices=[('Transporte Propio', 'Transporte Propio'), ('Flete pagado individual', 'Flete pagado individual'), ('Flete pagado colectivamente', 'Flete pagado colectivamente'), ('Otro', 'Otro')], default='Transporte Propio', max_length=100, null=True)),
                ('peso_lote', models.FloatField(default=0.0, help_text='Ingrese el peso EN LIBRAS del lote entregado por el productor/comerciante sin aplicar calificacion de humedad', null=True)),
                ('peso_lote_calificado', models.FloatField(default=0.0, help_text='Ingrese el peso EN LIBRAS del lote entregado por el productor/comerciante CON ESTIMACION/CALIFICACION DE HUMEDAD', null=True)),
                ('precio_lote_qq', models.FloatField(default=0.0, help_text='Ingrese el PRECIO PAGADO  por QUINTAL', null=True)),
                ('secado_en_cac_opciones', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=100, null=True)),
                ('tipo_secado_cac_opciones', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Secado Natural con Sol', 'Secado Natural con Sol'), ('Secado Natural en sombra', 'Secado Natural en sombra'), ('Secado a gas', 'Secado a gas')], default='Secado Natural con Sol', max_length=100, null=True)),
                ('modo_secado_cac_opciones', models.CharField(choices=[('Lona', 'Lona'), ('Marquesina', 'Marquesina'), ('Bandeja de secado', 'Bandeja de secado'), ('Otra', 'Otra')], default='Lona', max_length=100, null=True)),
                ('tiempo_secado_cac', models.CharField(help_text='Ingrese tiempo del proceso de secado: dias y horas para secado natural /horas para secado a gas', max_length=20, null=True)),
                ('tipo_transporte_cac_opciones', models.CharField(choices=[('Transporte Propio', 'Transporte Propio'), ('Flete pagado individual', 'Flete pagado individual'), ('Flete pagado colectivamente', 'Flete pagado colectivamente'), ('Otro', 'Otro')], default='Transporte Propio', max_length=100, null=True)),
                ('transportista_cac', models.CharField(help_text='Ingrese nombres del transportista', max_length=20, null=True)),
                ('fermentacion_cae_lote', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True)),
                ('tipo_fermentacion_cae_opciones', models.CharField(choices=[('Saco', 'Saco'), ('Caja de fermentación', 'Caja de fermentacion'), ('Lona', 'Lona'), ('Otro', 'Otro')], default='Saco', max_length=100, null=True)),
                ('tiempo_cae_fermentacion', models.CharField(help_text='Ingrese tiempo de fermentacion en dias y horas', max_length=20, null=True)),
                ('tipo_secado_cae_opciones', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Secado Natural con Sol', 'Secado Natural con Sol'), ('Secado Natural en sombra', 'Secado Natural en sombra'), ('Secado a gas', 'Secado a gas')], default='Secado Natural con Sol', max_length=100, null=True)),
                ('modo_secado_cae_opciones', models.CharField(choices=[('Lona', 'Lona'), ('Marquesina', 'Marquesina'), ('Bandeja de secado', 'Bandeja de secado'), ('Otra', 'Otra')], default='Lona', max_length=100, null=True)),
                ('tiempo_cae_secado', models.CharField(help_text='Ingrese tiempo del proceso de secado: dias y horas para secado natural /horas para secado a gas', max_length=20, null=True)),
                ('peso_lote_cae', models.FloatField(default=0.0, help_text='Ingrese el peso EN LIBRAS del lote entregado por el productor/comerciante sin aplicar calificacion de humedad', null=True)),
                ('peso_lote_cae_calificado', models.FloatField(default=0.0, help_text='Ingrese el peso EN LIBRAS del lote entregado por el productor/comerciante CON ESTIMACION/CALIFICACION DE HUMEDAD', null=True)),
                ('precio_lote_cae_qq', models.FloatField(default=0.0, help_text='Ingrese el PRECIO PAGADO  por QUINTAL', null=True)),
                ('contrato_exp', models.CharField(help_text='Ingrese numero de contrato de exportacion', max_length=15, null=True)),
                ('factura_exp', models.CharField(help_text='Ingrese numero de factura de exportación', max_length=17, null=True)),
                ('lote_exp', models.CharField(help_text='Ingrese tiempo de fermentacion en dias y horas', max_length=20, null=True)),
                ('numero_contenedores_exp', models.FloatField(default=0.0, help_text='Ingrese el número de contenedores (enteros o decimales)', null=True)),
                ('numero_sacos_exp', models.FloatField(default=0.0, help_text='Ingrese el número de sacos de 150 libras o 68 Kgs. (enteros o decimales)', null=True)),
                ('total_kgs_b_exp', models.FloatField(default=0.0, help_text='Ingrese el número total de kilogramos brutos comercializados', null=True)),
                ('total_kgs_n_exp', models.FloatField(default=0.0, help_text='Ingrese el número total de kilogramos netos comercializados', null=True)),
                ('fecha_embarque_exp', models.DateField(blank=True, null=True)),
                ('posiciones_exp_opciones', models.CharField(choices=[('Marzo', 'Marzo'), ('Julio', 'Julio'), ('Septiembre', 'Septiembre'), ('Diciembre', 'Diciembre')], default='Diciembre', max_length=100, null=True)),
                ('precio_fob_tm_exp', models.FloatField(default=0.0, help_text='Ingrese el precio promedio negociado por TM', null=True)),
                ('franquicia_exp', models.FloatField(default=0.0, help_text='Ingrese en decimales (2 decimales) el porcentaje de franquicia', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cliente_exp', models.CharField(help_text='Ingrese nombre del cliente', max_length=50, null=True)),
                ('fecha_sal_emb_exp', models.DateField(blank=True, null=True)),
                ('fecha_arr_emb_exp', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Centros de acopio comunitario',
            },
        ),
    ]
