# Generated by Django 3.0.6 on 2020-05-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transacciones_CAC',
            new_name='Registros_traz',
        ),
    ]
